// <auto-generated />
namespace FreelancingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initname));
        
        string IMigrationMetadata.Id
        {
            get { return "202105211255146_init-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
