// <auto-generated />
namespace FreelancingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixedColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202105240428191_fixedColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
